### PR TITLE
refactor: add delete button to draft gallery

### PR DESCRIPTION
**Pull request by crnkovic**
## Summary

https://app.clickup.com/t/86dqjt75x

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by alfonsobries — CHANGES_REQUESTED** [review]
Not specified on the ticket but think we shold add the toast added here https://github.com/ArdentHQ/dashbrd/pull/463

**Comment by crnkovic** [comment]
> Not specified on the ticket but think we shold add the toast added here #463

good idea, added the toast

**Comment by alfonsobries** [comment]
@crnkovic you are going to hate me sorry 😅

But on one of the tasks we removed the write `DELETE` to confirm when deleting drafts, so think we should do the same here 
image

image

**Review by ItsANameToo — APPROVED** [review]

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
when deleting a draft from the overview page, it shows the draft delete message. However, if you delete it from within the gallery it shows the regular delete gallery message instead. Both should show the draft message

overview:
image

when draft is open:
image

**Pull request merged**
