### PR TITLE
refactor: hook up local drafts and confirm delete modal

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

<del>Depends on #315</del>

<del>Blocked by https://github.com/ArdentHQ/dashbrd/pull/329</del>

Closes https://app.clickup.com/t/862kh23a1

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Comment by ItsANameToo** [comment]
can be updated now @alfonsobries

**Review by ItsANameToo — APPROVED** [review]

**Comment by ItsANameToo** [comment]
conflict @alfonsobries

**Comment by ItsANameToo** [comment]
@alfonsobries mind that https://github.com/ArdentHQ/dashbrd/pull/381 has been merged which introduces a GalleryDeleteButton, maybe you can reuse that on this PR as well

**Comment by alfonsobries** [comment]
@ItsANameToo we 

> @alfonsobries mind that #381 has been merged which introduces a GalleryDeleteButton, maybe you can reuse that on this PR as well

thinks that deservers his own task/pr, the button/modal from #381 is meant to be used with a gallery model which is not the case, also that pr adds the modal on every button (contrary to this pr that adds the modal globally)

We can potentially merge it in a single pr but maybe we should add a refactor task for that, wdyt?

**Comment by alfonsobries** [comment]
@ItsANameToo done

**Comment by ItsANameToo** [comment]
missing coverage @alfonsobries

**Comment by ItsANameToo** [comment]
seems to miss the `setConfirmationValue("")` line even though there is a test to handle open/close/open 🤔

**Pull request merged**
