### PR TITLE
feat: show previous month winners

### PR DESCRIPTION
**Pull request by goga-m**
## Summary
Depends on https://github.com/ArdentHQ/dashbrd/pull/534
https://app.clickup.com/t/86dqnpma8

The implementation is based on the `has_won_at` field of collections. It retrieves all collections that have `has_won_at` set and sorts them (descending order) by date & vote count.

Additionally, a new seeder is added for winner collections to fill `has_won_at` fields on random collections.

## Testing

1. Run `composer db:live`, so that the new seeder for winner collections will run.
2. Open `/collections/collection-of-the-month` and you should be able to see the previous winners' tables of the last two years. 

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Comment by ItsANameToo** [comment]
can be updated now @goga-m

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Some relatively minor UI points in relation to the Previous winner page.

1. When hovering over a year in the "Previous Winners" section, there should be a hover state where the text changes colour. See design
image

2. Currently can't select a Collection that was a previous winner. 
Design: 
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Table isn't formatted correctly at 960 and 768. "Volume" should be under the Collection name for example. 

Design
image

Implementation
image

**Review by samharperpittam — APPROVED** [review]

**Review by crnkovic — APPROVED** [review]

**Review by alfonsobries — APPROVED** [review]

**Comment by oXtxNt9U** [comment]
@goga-m merge conflict

**Pull request merged**
