### PR TITLE
feat: request signature for updating settings

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

Closes https://app.clickup.com/t/8678u945m

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — APPROVED** [review]

**Comment by samharperpittam** [comment]
Whilst I have approved this, i'm now wondering if we could handle "Set Defaults" a bit better. Currently, when you select "Set Defaults" in Settings, you're asked to connect your wallet. Once connected you then need to confirm the change within a modal. I'm wondering if it would be better to put the connection request on the "Confirm" button on the confirmation modal instead? 

image

**Comment by ItsANameToo** [comment]
@samharperpittam I think that flow would be better yeah, so you have button -> confirmation -> login and it gets applied

**Comment by ItsANameToo** [comment]
@alfonsobries actually, it might be better if we make navigation to the settings page require a signature. Then the user has to sign beforehand, which would remove the sign + perform action flow on that page as they are already past the signature at that point 🤔

**Comment by alfonsobries** [comment]
@ItsANameToo @samharperpittam now it asks for signature if user press "settings" link

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
