### PR TITLE
feat: implement gallery drafts limit modal

### PR DESCRIPTION
**Pull request by shahin-hq**
## Summary
Closes: https://app.clickup.com/t/862kh23bf

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Comment by ItsANameToo** [comment]
conflict @shahin-hq

**Review by alfonsobries — CHANGES_REQUESTED** [review]
The modal appeared as expected but it still saved the draft

https://github.com/ArdentHQ/dashbrd/assets/17262776/5c1241bd-b330-4261-a597-d59532592f49

**Comment by shahin-hq** [comment]
@alfonsobries Yes, I know, it was broken after the recent refactor of the galleries hook, this shouldn't be part of this task. I created a task for it https://app.clickup.com/t/86dqjt038

**Comment by shahin-hq** [comment]
@alfonsobries I had it [here](https://github.com/ArdentHQ/dashbrd/pull/315/files#diff-f55d30d9fb3e1e54a5716307a31cab8fea8c83a5718068b9a78e8f9b714c272eR79) but apparently it is broken after the recent draft refactor.

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
