### PR TITLE
feat: gallery page guest banner

### PR DESCRIPTION
**Pull request by patricio0312rev**
# [[gallery] add banner to gallery page](https://app.clickup.com/t/861nb5pwm)
https://app.clickup.com/t/861nb5pwm

## Summary

- A new guest banner for the gallery page has been created.
- This new component includes:
  - Translations for `common` and `pages`.
  - New `SVG` files for the backgrounds.
  - New `gallery-guest-banner` CSS custom class for the background of this new component.
  - New `GalleryGuestBanner` component.

## Steps to reproduce
1. Run the app in `local` mode.
2. Ensure you don't have a wallet connected to the app.
3. Go to home page and see the magic ✨ 

image

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — CHANGES_REQUESTED** [review]
@patricio0312rev - can we change this so it's viewable for all users regardless if they are connected or not. I don't think it's supposed to be a "guest only" feasture.

**Review by alfonsobries — CHANGES_REQUESTED** [review]
there is a small jump after the gallery is loaded



https://github.com/ArdentHQ/dashbrd/assets/17262776/2f4b3e17-1eb7-4da4-a12a-11aad2c44b3b

**Comment by alfonsobries** [comment]
button should be purple on mobile

design:
image

implementation

image

**Review by ItsANameToo — APPROVED** [review]

**Review by samharperpittam — CHANGES_REQUESTED** [review]
hmmm when viewing the Gallery page as a Guest and selecting the "Create Gallery" button, Metamask automatically attempts to connect without the user selecting "Connect Wallet". 

The design shows that selecting the Create Gallery button should route the user to an auth page where they can specifically select "Connect Wallet"

image

**Comment by ItsANameToo** [comment]
> When I click the "create gallery"' button as a guest and connect & sign, after the MM windows close, I remain in the galleries pages, instead of being redirected to the create gallery page. Is it expected?

https://github.com/ArdentHQ/dashbrd/pull/75

**Pull request merged**
