### PR TITLE
fix: remove duplicate collections list items when changing collection visibility status

### PR DESCRIPTION
**Pull request by goga-m**
## Summary
Closes https://app.clickup.com/t/8678j57ra

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Comment by crnkovic** [comment]
Hm interesting. How does this solve a problem when IDs are already unique in the database? 🤔

**Comment by ItsANameToo** [comment]
> @crnkovic it will render as e.g `220-0`, `220-1` ..., so I think the keys would be unique even if ids are the same 🤔

but `id` is unique, that's database id so you don't get `220-0`, `220-1` to begin with? 🤔

**Comment by crnkovic** [comment]
as if the database returns duplicated NFTs, i can see it throwing an error in that case

**Comment by ItsANameToo** [comment]
Although it does not show the error in devtools anymore on this branch, is does not update the table properly either 🤔 I hid one and it still shows up in the table when it refreshes to hide it. Clicking the details button on it causes it to show "unhide" while it's in the regular list view. Toggling `show hidden` is also broken at that point, as it will show the same table until you refresh the page
image

**Comment by ItsANameToo** [comment]
to reproduce:
- use a wallet with many collections
- scroll down to load new collections
- hide one after it loaded the images in that list of new collections
- no errors, but collection will remain and toggle no longer works as expected

**Review by shahin-hq — APPROVED** [review]

**Review by ItsANameToo — APPROVED** [review]

**Comment by ItsANameToo** [comment]
conflict @goga-m

**Pull request merged**
